// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfxgjvjaklvbefbqiftq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmeGdqdmpha2x2YmVmYnFpZnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzMwMzcsImV4cCI6MjA1ODIwOTAzN30.CtU6tUBZyR9HaCKBp58gZveG_Lm_6x5MLMV5CKK5nNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);